[package]
name = "wget_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full", "fs", "io-util"] }
hyper-native-tls = "0.3.0"

